# Kubernetes Secrets for Astronomer Remote Execution Agents
# Apply with: kubectl apply -f secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: astro-secrets
  namespace: astronomer-remote-agents
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded secrets
  # To encode: echo -n "your-secret" | base64

  # Database connection
  database-url: "" # echo -n "postgresql://user:pass@host:5432/db" | base64
  database-host: "" # echo -n "your-db-host" | base64
  database-user: "" # echo -n "your-db-user" | base64
  database-password: "" # echo -n "your-db-password" | base64
  database-name: "" # echo -n "your-db-name" | base64

  # Redis connection
  redis-url: "" # echo -n "redis://host:6379/0" | base64

  # Cloud provider credentials
  aws-access-key-id: ""
  aws-secret-access-key: ""
  gcp-service-account-key: ""

  # API keys
  slack-api-token: ""
  github-token: ""

  # Custom secrets
  custom-api-key: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: astro-config
  namespace: astronomer-remote-agents
data:
  # Non-sensitive configuration
  AIRFLOW__CORE__PARALLELISM: "32"
  AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: "16"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  CUSTOM_ENV_VAR: "production"